plugins:
  tslint:
    enabled: true
    config: tslint.json
  nodesecurity:
    enabled: true
  pmd:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  editorconfig:
    enabled: true
ratings:
  paths:
    - '**/*.js'
    - '**/*.ts'
    - '**/*.tsx'
    - '**/*.css'
exclude_paths:
  - 'node_modules/'
  - 'coverage/'
  - 'dist/'
exclude_patterns:
  - '**/*.test.tsx'
  - '**/*.test.ts'
  - '**/*.test.js'
  - '**/*.d.ts'
  - '**/*.conf.js'
