dist: trusty
sudo: required

language: node_js

node_js:
  - node

cache:
  yarn: true
  directories:
    - ./node_modules
    - $HOME/.cache/yarn
    - $HOME/.npm

matrix:
  fast_finish: true

install:
  - yarn

script:
  - yarn lint
  - yarn test
  - yarn build:prod

notifications:
  email:
    on_success: never
    on_failure: change
